# ConfigMap to store provider URLs
apiVersion: v1
kind: ConfigMap
metadata:
  name: gbfs-providers
  namespace: umob
data:
  provider1: "https://gbfs.api.ridedott.com/public/v2/aalst/gbfs.json"
  provider2: "https://www.sharedmobility.ch/gbfs.json"
  provider3: "https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_vr/gbfs.json"

---
# Deployment that uses the ConfigMap
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app
  namespace: umob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go-app
  template:
    metadata:
      labels:
        app: my-go-app
    spec:
      containers:
      - name: my-go-app
        image: umobacr.azurecr.io/my-go-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: PROVIDER1_URL
          valueFrom:
            configMapKeyRef:
              name: gbfs-providers
              key: provider1
        - name: PROVIDER2_URL
          valueFrom:
            configMapKeyRef:
              name: gbfs-providers
              key: provider2
        - name: PROVIDER3_URL
          valueFrom:
            configMapKeyRef:
              name: gbfs-providers
              key: provider3
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"

---
# Service for the Go app
apiVersion: v1
kind: Service
metadata:
  name: my-go-app-service
  namespace: umob
spec:
  selector:
    app: my-go-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
